# # Create checkbutton widgets
# xls_to_csv_var = tk.BooleanVar()
# xls_to_csv_checkbutton = create_checkbutton_widget(widgets_entry, 8, 0, 'Convert XLS to CSV', xls_to_csv_var)
# unzip_file_var = tk.BooleanVar()
# unzip_file_checkbutton = create_checkbutton_widget(widgets_entry, 11, 0, 'Unzip File', unzip_file_var)
# combine_files_var = tk.BooleanVar()
# combine_files_checkbutton = create_checkbutton_widget(widgets_entry, 14, 0, 'Combine Files', combine_files_var)
# remove_header_trailer_var = tk.BooleanVar()
# remove_header_trailer_checkbutton = create_checkbutton_widget(widgets_entry, 15, 0, 'Remove Header and Trailer', remove_header_trailer_var)
# additional_eol_var = tk.BooleanVar()
# additional_eol_checkbutton = create_checkbutton_widget(widgets_entry, 2, 1, 'Additional EOL', additional_eol_var)
# remove_additional_eol_var = tk.BooleanVar()
# remove_additional_eol_checkbutton = create_checkbutton_widget(widgets_entry, 3, 1, 'Remove Additional EOL', remove_additional_eol_var)
# add_record_id_var = tk.BooleanVar()
# add_record_id_checkbutton = create_checkbutton_widget(widgets_entry, 4, 1, 'Add Record ID', add_record_id_var)
# flatten_file_var = tk.BooleanVar()
# flatten_file_checkbutton = create_checkbutton_widget(widgets_entry, 6, 1, 'Flatten File', flatten_file_var)
# add_sequence_var = tk.BooleanVar()
# add_sequence_checkbutton = create_checkbutton_widget(widgets_entry, 7, 1, 'Add Sequence', add_sequence_var)
# fill_with_blank_lines_var = tk.BooleanVar()
# fill_with_blank_lines_checkbutton = create_checkbutton_widget(widgets_entry, 8, 1, 'Fill With Blank Lines', fill_with_blank_lines_var)
# delimit_fixed_width_var = tk.BooleanVar()
# delimit_fixed_width_checkbutton = create_checkbutton_widget(widgets_entry, 11, 1, 'Delimit Fixed Width', delimit_fixed_width_var)
# filter_records_var = tk.BooleanVar()
# filter_records_checkbutton = create_checkbutton_widget(widgets_entry, 14, 1, 'Filter Records', filter_records_var)
# inverted_filter_var = tk.BooleanVar()
# inverted_filter_checkbutton = create_checkbutton_widget(widgets_entry, 15, 1, 'Inverted Filter', inverted_filter_var)
# json_scrapping_needed_var = tk.BooleanVar()
# json_scrapping_needed_checkbutton = create_checkbutton_widget(widgets_entry, 1, 2, 'JSON Scrapping Needed', json_scrapping_needed_var)
# add_column_delimiter_var = tk.BooleanVar()
# add_column_delimiter_checkbutton = create_checkbutton_widget(widgets_entry, 3, 2, 'Add Column Delimiter', add_column_delimiter_var)
# escapeQuotes_var = tk.BooleanVar()
# escapeQuotes_checkbutton = create_checkbutton_widget(widgets_entry, 7, 2, 'Escape Quotes', escapeQuotes_var)
# insertFileControl_var = tk.BooleanVar()
# insertFileControl_checkbutton = create_checkbutton_widget(widgets_entry, 8, 2, 'Insert File Control', insertFileControl_var)
# deleteSourceFile_var = tk.BooleanVar()
# deleteSourceFile_checkbutton = create_checkbutton_widget(widgets_entry, 11, 2, 'Delete Source File', deleteSourceFile_var)
# Function to create and configure a checkbutton widget
def create_checkbutton_widget(parent, row, column, text, variable):
    checkbutton = ttk.Checkbutton(parent, text=text, variable=variable, onvalue=True, offvalue=False)
    checkbutton.grid(column=column, row=row, padx=5, pady=5, sticky='ew')
    return checkbutton